### ISSUE TITLE
[ParkRatingInspector] TypeError: undefined not callable (property 'parseInt' of [object Function])

### ISSUE THREAD

**Issue by LordGaav** [Basssiiie/OpenRCT2-ParkRatingInspector#15]
**Describe the bug**
On the latest stable version (0.3.5.1) the plugin does not work, and throws an error in the console.

**To reproduce**
1. Download the latest Linux .AppImage (version 0.3.5.1)
2. Install the plugin
3. Start a new scenario or load a save game
4. Try to open the plugin
5. Plugin does not open

**Expected behavior**
The plugin should open and work

**Screenshots**
Rather than screenshots, have this console output. I compiled my own version so it shows a stack trace, but normally it only shows the first line:

```
[ParkRatingInspector] TypeError: undefined not callable (property 'parseInt' of [object Function])
   -> i(): line 58
   -> <anonymous>: line 31
   -> <anonymous>: line 39
   -> <anonymous>: line 364
   -> W(): line 501
   -> <anonymous>: line 520
   -> <anonymous>: line 531
   -> window(): line 801
   -> <anonymous>: line 802
```

The (non-minified) relevant code is:

```js
    function i(s, c, h) {
        if (void 0 === c && (c = 0), void 0 === h && (h = 0), void 0 === s) return [ c, h ];
        if ('number' == typeof s) return [ s, 2 ];
        var l = s.trim(), f = l.length;
        if (f > 1) {
            var v = f - 1, y = void 0, x = l[v];
            if ('w' === x ? y = 2 : '%' === x ? y = 1 : f > 2 && (v = f - 2, 'x' === x && 'p' === l[v] && (y = 0)),
            void 0 !== y) return [ Number.parseInt(l.substring(0, v)), y ];
        }
        throw new Error('Value \'' + s + '\' is not a valid scale.');
    }
```

The `Number.parseInt` statement is what causes the error. This seems to originate from "openrct2-fluentui", and the line in question was very recently touched by you in https://github.com/Basssiiie/OpenRCT2-FluentUI/commit/524d9ab72513b8b6cce6ba5a65b45d353543e495 .

Are we missing some kind of bugfix, or update for this dependency?

**Comment by Basssiiie** [comment]
Hey LordGaav,

First of all, thank you very much for this detailed bug report. Unfortunately I'm not able to reproduce your bug on the latest OpenRCT2 release on my Windows machine. The plugin does work for me as expected. The code in question is my WIP UI library. `Number.parseInt` in question was changed to support floating point numbers, but the ParkRatingInspector does not use those and if it would, it should still not produce the error you're experiencing. (It would just put UI widgets in incorrect locations.)

The error indicates that `Number.parseInt` is `undefined`, which is weird because it should be a function from the ES5 standard library. It seems that in your case the implementation of this method is missing. Do you have any other plugins by any chance? Is the bug still present after temporarily moving all plugins except ParkRatingInspector out of your plugin folder? If that doesn't help, is it possible that Duktape (the Javascript engine OpenRCT2 uses) is out of date for some reason?

Thank you for your time.

**Comment by Basssiiie** [comment]
Additional note: it seems I can break my plugin by loading a second plugin that removes the `Number.parseInt` implementation.
```js
registerPlugin({
	name: 'Kill Number.parseInt',
	version: '1',
	authors: ['Basssiiie'],
	type: 'local',
	licence: 'MIT',
	main() {
		Number.parseInt = undefined;
		console.log("Bye bye parseInt");
	},
});
```
After loading this small plugin ParkRatingInspector stops working and I get the same error as you.

**Comment by LordGaav** [comment]
> The error indicates that `Number.parseInt` is `undefined`, which is weird because it should be a function from the ES5 standard library. It seems that in your case the implementation of this method is missing. Do you have any other plugins by any chance? Is the bug still present after temporarily moving all plugins except ParkRatingInspector out of your plugin folder? If that doesn't help, is it possible that Duktape (the Javascript engine OpenRCT2 uses) is out of date on your machine for some reason?

I just tried to remove all other plugins (just Ride.Price.Manager.js in my case), but I still get the same error. I'm running `6a73b95c0718a286c5a319ac964d156c3886832a4d20fd1cc3711cfbf982123b  OpenRCT2-0.3.5.1-linux-x86_64.AppImage` , if I get the chance I'll try the Windows version later.

**Comment by LordGaav** [comment]
Aha, it looks like support for Number.parseInt was introduced in Duktape 2.3:

```
More ES2015 support: Symbol.hasInstance, Symbol.toStringTag, Symbol.isConcatSpreadable, Symbol.toPrimitive, Proxy improvements, Number.EPSILON, Number.MIN_SAFE_INTEGER, Number.MAX_SAFE_INTEGER, Number.isFinite(), Number.isNaN(), Number.isSafeInteger(), Number.parseInt(), Number.parseFloat().
```

The build image for OpenRCT2 on Linux uses a docker image that's a year old, and the version there is 2.2 . That's why I also can't reproduce the issue when building OpenRCT2 myself (develop and 0.3.5.1) .

I'll open an issue in their repo and link to this issue.
